export const fileAllowExtension = [
  ".cs",
  ".java",
  ".py",
  ".html",
  ".css",
  ".js",
  ".php",
  ".rb",
  ".swift",
  ".rs",
  ".txt",
  ".doc",
  ".docx",
  ".png",
  ".pdf",
  ".jpg",
  ".zip",
];

export const extension2typeDictionary = {
  ".cs": "csharp",
  ".java": "java",
  ".py": "python",
  ".html": "html",
  ".css": "css",
  ".js": "javascript",
  ".php": "php",
  ".rb": "ruby",
  ".swift": "swift",
  ".rs": "rust",
  ".txt": "text",
  ".doc": "doc",
  ".docx": "docx",
  ".png": "png",
  ".pdf": "pdf",
  ".jpg": "jpg",
  ".zip": "zip",
};

export const type2extensionDictionary = {
  csharp: ".cs",
  java: ".java",
  python: ".py",
  html: ".html",
  css: ".css",
  javascript: ".js",
  php: ".php",
  ruby: ".rb",
  swift: ".swift",
  rust: ".rs",
  text: ".txt",
  doc: ".doc",
  docx: ".docx",
  png: ".png",
  pdf: ".pdf",
  jpg: ".jpg",
  zip: ".zip",
};

export const extension2viewType = {
  ".cs": "code",
  ".java": "code",
  ".py": "code",
  ".html": "code",
  ".css": "code",
  ".js": "code",
  ".php": "code",
  ".rb": "code",
  ".swift": "code",
  ".rs": "code",
  ".txt": "code",
  ".doc": "doc",
  ".docx": "doc",
  ".png": "image",
  ".pdf": "pdf",
  ".jpg": "image",
  ".zip": "zip",
};
